version: "3.8"

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      MYSQL_DATABASE: typescript_db
      MYSQL_ROOT_PASSWORD: elias1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    image: node:latest
    restart: always
    working_dir: /api
    ports:
      - "8000:8000"
    volumes:
      - ./:/api
    env_file: 
    - .env
    depends_on: 
     - mySQL
    command: npm run start:dev